<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>5b6ea228-389b-4ca9-9879-e94808caa293</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\NeoAndroidApp\NeoAndroidApp.csproj">
      <SetTargetFramework>TargetFramework=net10.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\NeoTelemetry.ApiService\NeoTelemetry.ApiService.csproj" />
    <ProjectReference Include="..\NeoTelemetry.Web\NeoTelemetry.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.0" />
  </ItemGroup>

</Project>
