<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Neo\Neo\Neo.csproj" />
    <ProjectReference Include="..\NeoTelemetry.ServiceDefaults\NeoTelemetry.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
